### ISSUE TITLE
web page log in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#13] opened 2015-10-31 00:21 UTC
```
What steps will reproduce the problem?
1.web page requires a log in
2.
3.

What is the expected output? What do you see instead?
the page for my web cam.
the log in page for the web site.

What version of the product are you using? On what operating system.
windows 8

Please provide any additional information below.

I would like to use my screen saver as a security cam. The camera is tied to 
D-link website. the website remembers my device when I log in through chrome or 
explorer but does not through the screen saver. it just sits at the log in page.


```

Original issue reported on code.google.com by `Ledeboer...@gmail.com` on 11 Dec 2014 at 11:05

**Comment by cwc** [comment] 2015-11-03 01:29
Dupe of #9.

**Closed by cwc** 2015-11-03 01:29 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
