### ISSUE TITLE
It needs to support preview mode 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#5] opened 2015-10-31 00:21 UTC
```
Please provide any additional information below.

so multiple monitor screensaver programs can use it on a second monitor (like 
UltraMon)
```

Original issue reported on code.google.com by `sean.s.s...@gmail.com` on 10 Aug 2012 at 5:53

**Comment by cwc** [comment] 2015-11-03 01:27
Dupe of #8.

**Closed by cwc** 2015-11-03 01:27 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
